import { StyleSheet } from 'react-native';
import { gentleShadow, line, mutedText, navy, pale, softShadow, text } from './theme';

export const styles = StyleSheet.create({
  page: {
    flex: 1,
    alignItems: 'stretch',
    justifyContent: 'flex-start',
    backgroundColor: '#FFFFFF',
  },
  phone: {
    flex: 1,
    width: '100%',
    height: '100%',
    overflow: 'hidden',
    backgroundColor: '#FFFFFF',
    borderRadius: 0,
  },
  screenTransition: {
    flex: 1,
  },
  scanOverlayScreen: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  scanOverlayHomePreview: {
    position: 'absolute',
    top: 0,
    left: 0,
    bottom: 0,
    width: 188,
    paddingTop: 28,
    paddingHorizontal: 14,
    opacity: 0.38,
    backgroundColor: '#FFFFFF',
  },
  scanSidePanel: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    width: 270,
    paddingHorizontal: 14,
    paddingTop: 8,
    backgroundColor: '#FFFFFF',
    borderLeftWidth: 1,
    borderLeftColor: line,
    shadowColor: '#000000',
    shadowOpacity: 0.18,
    shadowRadius: 18,
    shadowOffset: { width: -8, height: 0 },
    elevation: 12,
  },
  scanPanelHeader: {
    minHeight: 92,
    borderBottomWidth: 1,
    borderBottomColor: line,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingBottom: 12,
  },
  scanCloseButton: {
    width: 24,
    height: 34,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'transparent',
    marginRight: 4,
  },
  scanPanelSubtitle: {
    marginTop: 5,
    color: mutedText,
    fontSize: 12.5,
    fontWeight: '900',
    lineHeight: 17,
  },
  scanFullContent: {
    flex: 1,
    gap: 12,
    paddingBottom: 118,
  },
  scanFullPanel: {
    minHeight: 280,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 13,
    paddingVertical: 24,
  },
  scanFullKicker: {
    color: text,
    fontSize: 18,
    lineHeight: 24,
    fontWeight: '900',
  },
  scanFullStatusText: {
    color: mutedText,
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '900',
  },
  scanFullStatusGrid: {
    gap: 10,
    marginBottom: 28,
  },
  scanProgressSpacer: {
    flex: 1,
    minHeight: 20,
  },
  toastOverlay: {
    position: 'absolute',
    left: 16,
    right: 16,
    bottom: 64,
    minHeight: 58,
    borderRadius: 14,
    backgroundColor: 'rgba(87, 200, 121, 0.92)',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 18,
    paddingVertical: 12,
    zIndex: 999,
    elevation: 999,
    shadowColor: '#57C879',
    shadowOpacity: 0.18,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
  },
  toastOverlayAboveSheet: {
    bottom: 356,
  },
  toastPressable: {
    width: '100%',
    minHeight: 34,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 4,
  },
  toastText: {
    color: '#FFFFFF',
    fontSize: 13.5,
    lineHeight: 21,
    fontWeight: '900',
    textAlign: 'center',
    flexShrink: 1,
    width: '100%',
  },
  toastHintText: {
    marginTop: 2,
    color: 'rgba(255,255,255,0.82)',
    fontSize: 10.5,
    fontWeight: '800',
    textAlign: 'center',
  },
  shell: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  shellTint: {
    backgroundColor: '#F2FFF7',
  },
  modalScreenRoot: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  header: {
    height: 72,
    paddingTop: 0,
    paddingHorizontal: 18,
    borderBottomWidth: 0,
    justifyContent: 'center',
  },
  headerNoBack: {
    height: 72,
    borderBottomWidth: 0,
  },
  statusOnly: {
    height: 0,
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'space-between',
    paddingHorizontal: 18,
  },
  statusBarRow: {
    height: 0,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  statusTime: {
    color: text,
    fontSize: 15,
    fontWeight: '900',
  },
  statusDots: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingBottom: 3,
  },
  statusDot: {
    width: 7,
    height: 7,
    borderRadius: 4,
    backgroundColor: text,
  },
  headerTitleRow: {
    minHeight: 38,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 18,
  },
  headerTitleRowNoBack: {
    marginLeft: 8,
  },
  headerInsetRule: {
    height: 1,
    backgroundColor: line,
    marginTop: 8,
  },
  headerTitleRowSingle: {
    alignItems: 'center',
  },
  backGlyph: {
    width: 24,
    fontSize: 31,
    color: text,
    fontWeight: '700',
    lineHeight: 31,
  },
  backButton: {
    width: 30,
    height: 34,
    alignItems: 'flex-start',
    justifyContent: 'center',
  },
  headerText: {
    flex: 1,
    minWidth: 0,
  },
  headerTitleContent: {
    flex: 1,
    minWidth: 0,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 9,
  },
  headerTitleIcon: {
    width: 27,
    height: 27,
    alignItems: 'center',
    justifyContent: 'center',
  },
  title: {
    flexShrink: 1,
    color: text,
    fontSize: 21,
    lineHeight: 27,
    fontWeight: '800',
  },
  subtitle: {
    marginTop: 5,
    color: mutedText,
    fontSize: 12.5,
    fontWeight: '900',
    lineHeight: 17,
  },
  more: {
    color: text,
    fontSize: 22,
    fontWeight: '900',
  },
  content: {
    flex: 1,
  },
  contentInner: {
    padding: 18,
    paddingBottom: 92,
    gap: 12,
    flexGrow: 1,
  },
  contentInnerCompact: {
    paddingTop: 10,
  },
  contentInnerTightBottom: {
    paddingBottom: 32,
  },
  resultBottomSpacer: {
    height: 20,
  },
  inlineLoadingState: {
    flex: 1,
    minHeight: 360,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 16,
  },
  inlineLoadingText: {
    color: mutedText,
    fontSize: 15,
    fontWeight: '900',
  },
  serverDataLoadingState: {
    flex: 1,
    minHeight: 520,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 18,
  },
  serverDataLoadingText: {
    color: mutedText,
    fontSize: 18,
    lineHeight: 24,
    fontWeight: '900',
    textAlign: 'center',
  },
  heroSpacer: {
    height: 78,
  },
  logoImage: {
    width: 56,
    height: 56,
    borderRadius: 0,
  },
  logoImageMedium: {
    width: 118,
    height: 118,
    borderRadius: 0,
    alignSelf: 'center',
    marginTop: 18,
    marginBottom: 16,
  },
  logoImageLarge: {
    width: 248,
    height: 248,
    borderRadius: 0,
    alignSelf: 'center',
  },
  logoText: {
    flex: 1,
    color: text,
    fontSize: 25,
    fontWeight: '900',
  },
  logoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    minHeight: 58,
  },
  homeRule: {
    height: 1,
    backgroundColor: line,
    marginHorizontal: 0,
    marginTop: 0,
    marginBottom: 22,
  },
  heroTitle: {
    marginTop: 34,
    marginBottom: 24,
    color: text,
    textAlign: 'center',
    fontSize: 22,
    lineHeight: 32,
    fontWeight: '900',
  },
  heroTitleBrand: {
    color: navy,
  },
  primaryButton: {
    height: 50,
    borderRadius: 18,
    backgroundColor: navy,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 8,
    ...gentleShadow,
  },
  primaryButtonLower: {
    marginTop: 'auto',
  },
  primaryText: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '800',
  },
  outlineButton: {
    height: 48,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: line,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 8,
    backgroundColor: '#FFFFFF',
  },
  outlineButtonDanger: {
    borderColor: '#D92F36',
  },
  outlineText: {
    color: text,
    fontSize: 15,
    fontWeight: '800',
  },
  outlineTextDanger: {
    color: '#D92F36',
  },
  halfButton: {
    flex: 1,
  },
  consentRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginTop: 28,
    alignSelf: 'center',
  },
  privacyAgreeRow: {
    alignSelf: 'stretch',
    marginTop: 6,
  },
  initialConsentCard: {
    minHeight: 74,
    borderWidth: 1,
    borderColor: line,
    borderRadius: 14,
    backgroundColor: '#FFFFFF',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    gap: 13,
  },
  initialConsentTextBox: {
    flex: 1,
    gap: 6,
  },
  initialConsentTitle: {
    color: text,
    fontSize: 17,
    lineHeight: 21,
    fontWeight: '900',
  },
  initialConsentSub: {
    color: mutedText,
    fontSize: 12.5,
    lineHeight: 16,
    fontWeight: '800',
  },
  initialConsentLink: {
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 0,
    marginBottom: 10,
    width: 260,
    minHeight: 38,
  },
  initialActionBlock: {
    marginTop: 4,
    gap: 4,
  },
  initialConsentLinkTextBox: {
    alignItems: 'center',
    width: 260,
    alignSelf: 'center',
  },
  initialConsentTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  initialConsentLinkText: {
    color: text,
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '900',
  },
  initialConsentLinkLine: {
    marginTop: 9,
    width: 218,
    height: 1,
    backgroundColor: line,
  },
  consentText: {
    color: text,
    fontSize: 14,
    fontWeight: '900',
  },
  consentUnderlineRow: {
    paddingRight: 22,
    paddingBottom: 7,
    borderBottomWidth: 1,
    borderBottomColor: line,
  },
  helperText: {
    textAlign: 'center',
    color: mutedText,
    fontSize: 12,
    fontWeight: '800',
    lineHeight: 18,
  },
  checkbox: {
    width: 26,
    height: 26,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: navy,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  checkboxCompact: {
    width: 20,
    height: 20,
    borderRadius: 5,
    borderWidth: 1.3,
  },
  checkboxChecked: {
    backgroundColor: navy,
  },
  checkMark: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: '900',
    lineHeight: 22,
  },
  checkMarkCompact: {
    fontSize: 14,
    lineHeight: 17,
  },
  card: {
    borderWidth: 0,
    borderColor: line,
    borderRadius: 22,
    padding: 16,
    backgroundColor: '#FFFFFF',
    gap: 8,
    ...softShadow,
  },
  cardTint: {
    backgroundColor: pale,
  },
  privacyStatusCard: {
    minHeight: 72,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 18,
  },
  privacyStatusText: {
    marginTop: 8,
    color: text,
    fontSize: 19,
    fontWeight: '900',
  },
  privacyCheckIcon: {
    color: text,
    fontSize: 34,
    fontWeight: '900',
  },
  privacyCombinedCard: {
    minHeight: 366,
    paddingHorizontal: 18,
    paddingVertical: 22,
    gap: 28,
  },
  privacyBlock: {
    gap: 14,
  },
  privacyInfoCard: {
    minHeight: 142,
    paddingHorizontal: 18,
    paddingVertical: 18,
    gap: 18,
  },
  privacyRetentionCard: {
    minHeight: 82,
    paddingHorizontal: 18,
    paddingVertical: 16,
    gap: 12,
  },
  capacityCard: {
    minHeight: 82,
    justifyContent: 'center',
    borderRadius: 20,
    paddingHorizontal: 15,
  },
  capacityCardRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 14,
  },
  capacityUsageBox: {
    width: 116,
    gap: 8,
  },
  capacityUsageText: {
    color: navy,
    textAlign: 'right',
    fontSize: 12,
    fontWeight: '800',
  },
  capacityUsageTrack: {
    height: 9,
    borderRadius: 9,
    backgroundColor: '#EAF9EF',
    overflow: 'hidden',
  },
  capacityUsageFill: {
    height: '100%',
    borderRadius: 9,
    backgroundColor: navy,
  },
  homeActionSpacer: {
    height: 0,
  },
  homeSummaryCard: {
    minHeight: 154,
    justifyContent: 'space-between',
    paddingVertical: 16,
  },
  homeSummaryCapacityRow: {
    minHeight: 60,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 14,
  },
  homeSummaryValue: {
    color: text,
    fontSize: 30,
    fontWeight: '800',
  },
  homeSummaryCapacityLabel: {
    minWidth: 110,
    color: text,
    fontSize: 18,
    lineHeight: 24,
    fontWeight: '800',
  },
  homeTrashIconButton: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: line,
    ...gentleShadow,
  },
  homeTrashIconText: {
    fontSize: 24,
    lineHeight: 30,
  },
  homeEmptySummary: {
    minHeight: 96,
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 12,
    justifyContent: 'center',
    gap: 12,
  },
  homeEmptyTitle: {
    color: mutedText,
    fontSize: 13,
    fontWeight: '900',
    textAlign: 'center',
  },
  homeEmptyDesc: {
    color: mutedText,
    fontSize: 12,
    lineHeight: 17,
    fontWeight: '800',
  },
  sectionTitle: {
    color: text,
    fontSize: 18,
    fontWeight: '900',
    marginTop: 4,
  },
  sectionHeaderRow: {
    marginTop: 4,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  sectionRefreshButton: {
    width: 36,
    height: 36,
    alignItems: 'center',
    justifyContent: 'center',
  },
  sectionRefreshButtonDisabled: {
    opacity: 0.55,
  },
  body: {
    color: text,
    fontSize: 15,
    lineHeight: 27,
    fontWeight: '800',
  },
  privacyBody: {
    color: text,
    fontSize: 13.5,
    lineHeight: 24,
    fontWeight: '800',
  },
  infoRow: {
    minHeight: 72,
    borderWidth: 0,
    borderColor: line,
    borderRadius: 18,
    paddingHorizontal: 14,
    paddingVertical: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    backgroundColor: '#FFFFFF',
    ...gentleShadow,
  },
  permissionRow: {
    minHeight: 72,
    borderWidth: 0,
    borderColor: line,
    borderRadius: 18,
    paddingHorizontal: 14,
    paddingVertical: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    backgroundColor: '#FFFFFF',
    ...gentleShadow,
  },
  permissionDetailButton: {
    width: 42,
    height: 42,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: -8,
  },
  permissionFeatureCard: {
    minHeight: 70,
    borderWidth: 0,
    borderColor: line,
    borderRadius: 18,
    paddingHorizontal: 14,
    paddingVertical: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    backgroundColor: '#FFFFFF',
    ...gentleShadow,
  },
  permissionFeatureIcon: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: pale,
    borderWidth: 1,
    borderColor: line,
    alignItems: 'center',
    justifyContent: 'center',
  },
  permissionFeatureCheck: {
    color: navy,
    fontSize: 16,
    fontWeight: '900',
    lineHeight: 19,
  },
  permissionBlockedCard: {
    minHeight: 78,
    paddingHorizontal: 16,
    paddingVertical: 14,
    gap: 8,
  },
  permissionBlockedText: {
    color: mutedText,
    fontSize: 13,
    lineHeight: 19,
    fontWeight: '800',
  },
  permissionReasonCard: {
    marginTop: 8,
    paddingHorizontal: 20,
    paddingVertical: 20,
    gap: 18,
    minHeight: 390,
  },
  pushPermissionReasonCard: {
    marginTop: 0,
    paddingHorizontal: 18,
    paddingVertical: 16,
    gap: 14,
    minHeight: 0,
  },
  permissionReasonSection: {
    gap: 9,
  },
  permissionReasonDescription: {
    color: text,
    fontSize: 13,
    lineHeight: 20,
    fontWeight: '900',
  },
  permissionReasonTitle: {
    color: text,
    fontSize: 15,
    lineHeight: 20,
    fontWeight: '900',
  },
  permissionReasonText: {
    color: text,
    fontSize: 13,
    lineHeight: 22,
    fontWeight: '800',
  },
  permissionReasonNote: {
    borderTopWidth: 1,
    borderTopColor: line,
    paddingTop: 14,
    marginTop: 2,
  },
  permissionReasonNoteText: {
    color: navy,
    fontSize: 12,
    lineHeight: 18,
    fontWeight: '900',
  },
  infoMain: {
    flex: 1,
    gap: 5,
  },
  infoTitle: {
    color: text,
    fontSize: 16,
    fontWeight: '900',
  },
  infoDesc: {
    color: mutedText,
    fontSize: 12,
    fontWeight: '800',
    lineHeight: 17,
  },
  chevron: {
    color: text,
    fontSize: 28,
    fontWeight: '900',
  },
  rowRight: {
    color: navy,
    fontSize: 12,
    fontWeight: '900',
  },
  rowRightMuted: {
    color: mutedText,
  },
  flexGrow: {
    flex: 1,
    minHeight: 120,
  },
  pushPermissionButtonSpacer: {
    height: 18,
  },
  centerTitle: {
    color: text,
    textAlign: 'center',
    fontSize: 20,
    fontWeight: '900',
    marginVertical: 12,
  },
  centerTitleSpace: {
    height: 52,
  },
  connectedIconWrap: {
    width: 112,
    height: 112,
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 40,
    marginBottom: 10,
  },
  connectedRing: {
    position: 'absolute',
    width: 108,
    height: 108,
    borderRadius: 54,
    borderWidth: 5,
    borderColor: line,
  },
  connectedIconInner: {
    width: 84,
    height: 84,
    borderRadius: 42,
    backgroundColor: pale,
    borderWidth: 1,
    borderColor: line,
    alignItems: 'center',
    justifyContent: 'center',
  },
  connectedProgressText: {
    color: navy,
    fontSize: 20,
    fontWeight: '900',
  },
  connectedCheckText: {
    color: navy,
    fontSize: 42,
    lineHeight: 48,
    fontWeight: '900',
  },
  connectedButtonReveal: {
    marginTop: 'auto',
  },
  connectedButtonPlaceholder: {
    marginTop: 'auto',
    height: 50,
  },
  connectedRightSlot: {
    width: 34,
    minHeight: 18,
    alignItems: 'flex-end',
    justifyContent: 'center',
  },
  statusLight: {
    width: 11,
    height: 11,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.85)',
  },
  statusLightGreen: {
    backgroundColor: navy,
  },
  statusLightRed: {
    backgroundColor: '#D94A4A',
  },
  statusLightYellow: {
    backgroundColor: '#F0C342',
  },
  centerBody: {
    color: text,
    textAlign: 'center',
    fontSize: 14,
    fontWeight: '700',
    lineHeight: 22,
    marginVertical: 18,
  },
  centerIcon: {
    width: 96,
    height: 96,
    borderRadius: 48,
    backgroundColor: pale,
    borderWidth: 1.5,
    borderColor: line,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    marginTop: 40,
  },
  centerIconText: {
    color: navy,
    fontSize: 42,
    fontWeight: '900',
  },
  previewCard: {
    height: 190,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: line,
    backgroundColor: pale,
    alignItems: 'center',
    justifyContent: 'center',
  },
  previewText: {
    color: mutedText,
    fontSize: 15,
    fontWeight: '900',
  },
  emptyStateCard: {
    minHeight: 220,
    borderRadius: 16,
    borderWidth: 0,
    borderColor: line,
    backgroundColor: pale,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 20,
    gap: 10,
    ...gentleShadow,
  },
  emptyStateIcon: {
    width: 54,
    height: 54,
    borderRadius: 27,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: line,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 2,
  },
  emptyStateIconText: {
    color: mutedText,
    fontSize: 24,
    lineHeight: 28,
    fontWeight: '900',
  },
  emptyStateTitle: {
    color: text,
    fontSize: 17,
    lineHeight: 23,
    fontWeight: '900',
    textAlign: 'center',
  },
  emptyStateDesc: {
    color: mutedText,
    fontSize: 13,
    lineHeight: 20,
    fontWeight: '800',
    textAlign: 'center',
  },
  onboardingButtonReveal: {
    marginTop: 'auto',
  },
  onboardingButtonPlaceholder: {
    marginTop: 'auto',
    height: 50,
  },
  onboardingDescriptionRow: {
    minHeight: 52,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    gap: 10,
    alignSelf: 'stretch',
    paddingLeft: 42,
    paddingRight: 24,
    marginVertical: 12,
  },
  onboardingDescriptionIcon: {
    width: 34,
    alignItems: 'center',
    justifyContent: 'center',
  },
  onboardingDescriptionText: {
    flexShrink: 1,
    marginVertical: 0,
    textAlign: 'left',
  },
  auraFeelReveal: {
    minHeight: 48,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 0,
    marginBottom: 6,
  },
  auraFeelPlaceholder: {
    minHeight: 48,
    marginTop: 0,
    marginBottom: 6,
  },
  auraFeelText: {
    color: text,
    textAlign: 'center',
    fontSize: 20,
    lineHeight: 28,
    fontWeight: '900',
    letterSpacing: -0.2,
  },
  auraFeelTextRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 5,
  },
  auraFeelBrand: {
    color: navy,
    fontSize: 24,
    textShadowColor: '#DDF8E6',
    textShadowRadius: 8,
  },
  ghostPreviewCard: {
    height: 330,
    borderRadius: 24,
    borderWidth: 0,
    borderColor: line,
    backgroundColor: '#FFFFFF',
    padding: 16,
    gap: 10,
    overflow: 'hidden',
    ...softShadow,
  },
  ghostPreviewHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  ghostPreviewTitle: {
    color: text,
    fontSize: 18,
    fontWeight: '900',
  },
  onboardingIntroContent: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 24,
  },
  onboardingIntroTextBox: {
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 18,
  },
  onboardingIntroTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    flexWrap: 'wrap',
    gap: 4,
  },
  onboardingIntroTitleText: {
    color: text,
    fontSize: 15,
    lineHeight: 22,
    fontWeight: '900',
  },
  onboardingIntroBody: {
    color: text,
    textAlign: 'center',
    fontSize: 20,
    lineHeight: 29,
    fontWeight: '900',
  },
  ghostPreviewPercent: {
    color: navy,
    fontSize: 13,
    fontWeight: '900',
  },
  onboardingMetricGrid: {
    height: 76,
    flexDirection: 'row',
    gap: 12,
  },
  onboardingMetricCard: {
    flex: 1,
    borderWidth: 0,
    borderColor: line,
    borderRadius: 18,
    backgroundColor: pale,
    paddingHorizontal: 14,
    paddingVertical: 11,
    justifyContent: 'center',
    gap: 5,
  },
  onboardingMetricLabel: {
    color: mutedText,
    fontSize: 9.5,
    fontWeight: '900',
  },
  onboardingMetricValue: {
    color: text,
    fontSize: 20,
    fontWeight: '900',
  },
  ghostDataPanel: {
    flex: 1,
    borderRadius: 20,
    borderWidth: 0,
    borderColor: line,
    backgroundColor: 'transparent',
    padding: 0,
    gap: 8,
    overflow: 'hidden',
  },
  ghostDataRow: {
    minHeight: 40,
    borderRadius: 16,
    paddingHorizontal: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 9,
    backgroundColor: pale,
  },
  ghostDataRowActive: {
    backgroundColor: '#E9FFF0',
    borderWidth: 0,
    borderColor: '#CDEFD8',
  },
  ghostDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: line,
  },
  ghostDotActive: {
    backgroundColor: navy,
  },
  ghostDataLabel: {
    color: text,
    fontSize: 12,
    fontWeight: '900',
  },
  ghostDataMeta: {
    color: mutedText,
    fontSize: 10,
    fontWeight: '800',
  },
  ghostDataStatus: {
    color: mutedText,
    fontSize: 17,
    lineHeight: 18,
    fontWeight: '900',
  },
  ghostDataStatusActive: {
    color: navy,
  },
  ghostProtectedText: {
    alignSelf: 'center',
    color: text,
    fontSize: 11,
    lineHeight: 14,
    fontWeight: '900',
    textDecorationLine: 'underline',
  },
  ghostCandidateRow: {
    minHeight: 48,
    borderRadius: 12,
    backgroundColor: '#FFFFFF',
    borderWidth: 0,
    borderColor: line,
    paddingHorizontal: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  ghostCandidateIcon: {
    fontSize: 23,
  },
  ghostCandidateTitle: {
    color: text,
    fontSize: 13,
    fontWeight: '900',
  },
  ghostCandidateDesc: {
    color: mutedText,
    fontSize: 10,
    fontWeight: '800',
  },
  carbonPreviewCard: {
    height: 330,
    borderRadius: 24,
    borderWidth: 0,
    borderColor: line,
    backgroundColor: '#FFFFFF',
    padding: 16,
    gap: 10,
    overflow: 'hidden',
    ...softShadow,
  },
  carbonTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  carbonTopLabel: {
    color: text,
    fontSize: 18,
    fontWeight: '900',
  },
  historyTotalMiniCard: {
    minHeight: 82,
    borderWidth: 0,
    borderColor: line,
    borderRadius: 18,
    backgroundColor: pale,
    paddingHorizontal: 14,
    paddingVertical: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  historyTotalMiniValue: {
    color: text,
    fontSize: 26,
    fontWeight: '900',
  },
  historyMiniPill: {
    minHeight: 24,
    borderRadius: 12,
    backgroundColor: '#E9FFF0',
    paddingHorizontal: 9,
    alignItems: 'center',
    justifyContent: 'center',
  },
  historyMiniPillText: {
    color: navy,
    fontSize: 10,
    fontWeight: '900',
  },
  historyGraphMiniCard: {
    flex: 1,
    borderWidth: 0,
    borderColor: line,
    borderRadius: 18,
    backgroundColor: pale,
    paddingHorizontal: 14,
    paddingVertical: 12,
    gap: 10,
  },
  historyGraphMiniTitle: {
    color: text,
    fontSize: 13,
    fontWeight: '900',
  },
  historyMiniUnit: {
    color: mutedText,
    fontSize: 9,
    fontWeight: '900',
  },
  historyMiniSvgWrap: {
    flex: 1,
    minHeight: 112,
  },
  historyMiniGraphArea: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'stretch',
    gap: 6,
  },
  historyMiniYAxis: {
    width: 17,
    justifyContent: 'space-between',
    paddingTop: 5,
    paddingBottom: 14,
  },
  historyMiniAxisText: {
    color: mutedText,
    fontSize: 8,
    fontWeight: '900',
    textAlign: 'right',
  },
  historyMiniPlot: {
    flex: 1,
    position: 'relative',
    borderBottomWidth: 1,
    borderBottomColor: line,
    height: 112,
  },
  historyMiniGridTop: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 8,
    height: 1,
    backgroundColor: line,
  },
  historyMiniGridMiddle: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 48,
    height: 1,
    backgroundColor: line,
  },
  historyMiniGridBottom: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 88,
    height: 1,
    backgroundColor: line,
  },
  historyMiniLineLayer: {
    position: 'absolute',
    left: 10,
    top: 8,
    width: 196,
    height: 88,
  },
  historyMiniLineSegment: {
    position: 'absolute',
    height: 2.5,
    borderRadius: 3,
    backgroundColor: navy,
    transformOrigin: '0px 1.25px',
  },
  historyMiniPointWrap: {
    position: 'absolute',
    width: 42,
    alignItems: 'center',
    gap: 3,
  },
  historyMiniPointValue: {
    color: navy,
    fontSize: 8.5,
    fontWeight: '900',
  },
  historyMiniPoint: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: navy,
    borderWidth: 1.5,
    borderColor: '#FFFFFF',
  },
  historyMiniMonthLayer: {
    position: 'absolute',
    left: 10,
    right: 0,
    bottom: 0,
    height: 14,
  },
  historyMiniMonthText: {
    position: 'absolute',
    width: 32,
    color: mutedText,
    fontSize: 8.5,
    fontWeight: '900',
    textAlign: 'center',
  },
  carbonMeterTrack: {
    height: 16,
    borderRadius: 8,
    backgroundColor: '#EAF9EF',
    overflow: 'hidden',
  },
  carbonMeterFill: {
    height: 16,
    borderRadius: 8,
    backgroundColor: navy,
  },
  carbonResultCard: {
    flex: 1,
    borderRadius: 14,
    backgroundColor: '#FFFFFF',
    borderWidth: 0,
    borderColor: line,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 7,
  },
  carbonLeaf: {
    fontSize: 32,
  },
  carbonResultNumber: {
    color: navy,
    fontSize: 20,
    fontWeight: '900',
  },
  carbonResultDesc: {
    color: mutedText,
    fontSize: 11,
    fontWeight: '800',
  },
  cardLabel: {
    color: mutedText,
    fontSize: 14,
    fontWeight: '900',
  },
  textStrong: {
    color: text,
  },
  cardTitle: {
    color: text,
    fontSize: 18,
    fontWeight: '900',
  },
  bigNumber: {
    color: text,
    fontSize: 28,
    fontWeight: '900',
  },
  meta: {
    color: mutedText,
    fontSize: 12.5,
    fontWeight: '800',
    lineHeight: 18,
  },
  divider: {
    height: 1,
    backgroundColor: line,
    marginVertical: 6,
  },
  pill: {
    paddingHorizontal: 14,
    paddingVertical: 6,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: line,
    color: text,
    fontSize: 12,
    fontWeight: '900',
  },
  homeDetailPill: {
    paddingHorizontal: 10,
    height: 24,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: line,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  homeDetailAction: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 5,
  },
  homeDetailText: {
    color: navy,
    fontSize: 11,
    fontWeight: '900',
  },
  homeChevron: {
    color: text,
    fontSize: 24,
    lineHeight: 24,
    fontWeight: '900',
  },
  resultText: {
    color: text,
    fontSize: 22,
    fontWeight: '900',
  },
  chipWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginVertical: 8,
  },
  chip: {
    paddingHorizontal: 15,
    height: 34,
    borderRadius: 17,
    borderWidth: 1,
    borderColor: line,
    backgroundColor: pale,
    alignItems: 'center',
    justifyContent: 'center',
  },
  chipSelected: {
    borderColor: navy,
    backgroundColor: navy,
  },
  removableChip: {
    flexDirection: 'row',
    gap: 7,
    paddingRight: 11,
  },
  chipText: {
    color: navy,
    fontSize: 12,
    fontWeight: '900',
  },
  chipTextSelected: {
    color: '#FFFFFF',
  },
  removeChipText: {
    color: navy,
    fontSize: 15,
    lineHeight: 16,
    fontWeight: '900',
  },
  attachmentOptionCard: {
    minHeight: 68,
    borderWidth: 1,
    borderColor: line,
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    backgroundColor: pale,
  },
  attachmentInlineCard: {
    minHeight: 48,
    borderWidth: 1,
    borderColor: line,
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: pale,
  },
  attachmentInlineCardLarge: {
    minHeight: 70,
    alignItems: 'center',
    gap: 12,
  },
  scanSourceCard: {
    minHeight: 78,
    borderWidth: 0,
    borderColor: line,
    borderRadius: 18,
    paddingHorizontal: 14,
    paddingVertical: 13,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    backgroundColor: '#FFFFFF',
    ...gentleShadow,
  },
  scanSourceCardSelected: {
    backgroundColor: pale,
    borderColor: line,
  },
  scanSummaryCard: {
    minHeight: 68,
    borderWidth: 1,
    borderColor: line,
    borderRadius: 10,
    paddingHorizontal: 16,
    paddingVertical: 13,
    backgroundColor: pale,
    justifyContent: 'center',
  },
  folderSearchBox: {
    height: 48,
    borderWidth: 1,
    borderColor: line,
    borderRadius: 10,
    paddingHorizontal: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    backgroundColor: '#FFFFFF',
  },
  searchIcon: {
    color: navy,
    fontSize: 17,
    fontWeight: '900',
  },
  searchPlaceholder: {
    color: mutedText,
    fontSize: 13,
    fontWeight: '900',
  },
  folderSearchInput: {
    flex: 1,
    color: text,
    fontSize: 13,
    fontWeight: '900',
    paddingVertical: 0,
  },
  folderSelectAllCard: {
    minHeight: 64,
    borderWidth: 0,
    borderColor: line,
    borderRadius: 18,
    paddingHorizontal: 16,
    paddingVertical: 13,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    backgroundColor: '#FFFFFF',
    ...gentleShadow,
  },
  folderSelectAllInlineRow: {
    minHeight: 42,
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    gap: 10,
    paddingHorizontal: 2,
    paddingVertical: 2,
  },
  folderSelectAllTitle: {
    color: text,
    fontSize: 18,
    fontWeight: '900',
  },
  folderBreadcrumbCard: {
    minHeight: 34,
    paddingHorizontal: 4,
    paddingVertical: 3,
    justifyContent: 'center',
  },
  folderBreadcrumbClickableRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 6,
  },
  folderBreadcrumbRule: {
    height: 1,
    marginHorizontal: 7,
    backgroundColor: line,
  },
  folderBreadcrumbDivider: {
    color: text,
    fontSize: 16,
    fontWeight: '900',
  },
  folderBreadcrumbTitle: {
    color: navy,
    fontSize: 16,
    fontWeight: '900',
  },
  folderBreadcrumbAncestor: {
    color: text,
  },
  folderBreadcrumbText: {
    color: mutedText,
    fontSize: 11.5,
    lineHeight: 16,
    fontWeight: '800',
  },
  currentLocationCard: {
    minHeight: 62,
    borderWidth: 1,
    borderColor: line,
    borderRadius: 10,
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: pale,
    justifyContent: 'center',
  },
  folderRow: {
    minHeight: 66,
    borderWidth: 0,
    borderColor: line,
    borderRadius: 18,
    paddingHorizontal: 14,
    paddingVertical: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    backgroundColor: '#FFFFFF',
    ...gentleShadow,
  },
  folderRowSelected: {
    borderColor: navy,
    backgroundColor: pale,
  },
  folderOutlineIcon: {
    width: 30,
    height: 28,
    justifyContent: 'flex-end',
  },
  fileIconFrame: {
    width: 32,
    height: 32,
    alignItems: 'center',
    justifyContent: 'center',
  },
  fileIconFrameCompact: {
    width: 26,
    height: 26,
  },
  folderOutlineTab: {
    position: 'absolute',
    left: 3,
    top: 2,
    width: 14,
    height: 9,
    borderTopLeftRadius: 4,
    borderTopRightRadius: 5,
    borderWidth: 2,
    borderBottomWidth: 0,
    borderColor: navy,
    backgroundColor: '#FFFFFF',
  },
  folderOutlineBody: {
    width: 30,
    height: 22,
    borderRadius: 7,
    borderWidth: 2,
    borderColor: navy,
    backgroundColor: '#FFFFFF',
  },
  folderIcon: {
    width: 38,
    height: 38,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: line,
    backgroundColor: pale,
    alignItems: 'center',
    justifyContent: 'center',
  },
  folderIconText: {
    color: navy,
    fontSize: 16,
    fontWeight: '900',
  },
  folderNavigateButton: {
    width: 34,
    height: 34,
    borderRadius: 17,
    borderWidth: 1,
    borderColor: line,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: -2,
  },
  folderNavigateText: {
    color: navy,
    fontSize: 26,
    lineHeight: 28,
    fontWeight: '900',
    marginTop: -2,
  },
  folderTitleLine: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  folderTitleText: {
    flex: 1,
    color: text,
    fontSize: 18,
    fontWeight: '900',
  },
  folderSizeText: {
    color: mutedText,
    fontSize: 13,
    fontWeight: '900',
  },
  monthConditionRow: {
    minHeight: 76,
    borderWidth: 1,
    borderColor: line,
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    backgroundColor: '#FFFFFF',
  },
  monthStepper: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  monthStepButton: {
    width: 30,
    height: 30,
    borderRadius: 15,
    borderWidth: 0,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'transparent',
  },
  monthStepText: {
    color: navy,
    fontSize: 18,
    lineHeight: 20,
    fontWeight: '900',
  },
  sheetKeyboardAvoider: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    justifyContent: 'flex-end',
  },
  periodMonthSheet: {
    position: 'absolute',
    left: 16,
    right: 16,
    bottom: 18,
    borderRadius: 22,
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 18,
    paddingTop: 10,
    paddingBottom: 24,
    gap: 14,
    borderWidth: 0,
    borderColor: line,
    shadowColor: '#000000',
    shadowOpacity: 0.14,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: -4 },
    elevation: 10,
  },
  keywordSheetDesc: {
    textAlign: 'center',
  },
  periodMonthControl: {
    minHeight: 58,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  periodMonthInputGroup: {
    flex: 1,
    minHeight: 52,
    borderWidth: 1,
    borderColor: line,
    borderRadius: 10,
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  periodMonthInput: {
    width: 44,
    height: 36,
    borderWidth: 1,
    borderColor: line,
    borderRadius: 8,
    backgroundColor: '#FFFFFF',
    color: text,
    fontSize: 17,
    fontWeight: '900',
    textAlign: 'center',
    paddingHorizontal: 0,
    paddingVertical: 0,
  },
  periodHeroCard: {
    minHeight: 70,
    borderWidth: 1,
    borderColor: line,
    borderRadius: 10,
    paddingHorizontal: 16,
    paddingVertical: 14,
    backgroundColor: pale,
    justifyContent: 'center',
  },
  periodOptionGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  periodOption: {
    width: '47%',
    height: 44,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: line,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  periodOptionSelected: {
    backgroundColor: navy,
    borderColor: navy,
  },
  periodOptionText: {
    color: navy,
    fontSize: 13,
    fontWeight: '900',
  },
  periodOptionTextSelected: {
    color: '#FFFFFF',
  },
  yearRangeSummary: {
    minHeight: 58,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: line,
    backgroundColor: pale,
    paddingHorizontal: 16,
    paddingVertical: 11,
    marginTop: 14,
    marginBottom: 18,
  },
  yearRangeLabel: {
    color: mutedText,
    fontSize: 11,
    fontWeight: '900',
    marginBottom: 4,
  },
  yearRangeValue: {
    color: text,
    fontSize: 17,
    fontWeight: '900',
  },
  periodInputPanel: {
    borderWidth: 1,
    borderColor: line,
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 12,
    backgroundColor: '#FFFFFF',
    gap: 8,
    marginBottom: 16,
  },
  periodInputLine: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  periodInputLabel: {
    width: 34,
    color: text,
    fontSize: 12,
    fontWeight: '900',
  },
  periodSmallInput: {
    width: 62,
    height: 34,
    borderWidth: 1,
    borderColor: line,
    borderRadius: 8,
    color: text,
    fontSize: 13,
    fontWeight: '900',
    textAlign: 'center',
    paddingVertical: 0,
  },
  periodTinyInput: {
    width: 42,
    height: 34,
    borderWidth: 1,
    borderColor: line,
    borderRadius: 8,
    color: text,
    fontSize: 13,
    fontWeight: '900',
    textAlign: 'center',
    paddingVertical: 0,
  },
  periodUnit: {
    color: mutedText,
    fontSize: 12,
    fontWeight: '900',
  },
  yearSliderWrap: {
    paddingHorizontal: 4,
    paddingTop: 8,
    paddingBottom: 10,
  },
  yearSliderTrack: {
    width: 226,
    height: 30,
    borderRadius: 15,
    backgroundColor: line,
    alignSelf: 'center',
    marginTop: 22,
    marginBottom: 34,
    justifyContent: 'center',
  },
  yearSliderSelected: {
    position: 'absolute',
    top: 11,
    height: 8,
    borderRadius: 8,
    backgroundColor: navy,
  },
  yearHandle: {
    position: 'absolute',
    top: -7,
    width: 44,
    height: 44,
    borderRadius: 22,
    borderWidth: 3,
    borderColor: '#FFFFFF',
    backgroundColor: navy,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: navy,
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 4,
  },
  yearHandleText: {
    color: '#FFFFFF',
    fontSize: 9,
    fontWeight: '900',
  },
  yearTickRow: {
    width: 248,
    alignSelf: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  yearTickText: {
    color: mutedText,
    fontSize: 10,
    fontWeight: '800',
  },
  inputRow: {
    height: 50,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: line,
    flexDirection: 'row',
    alignItems: 'center',
    paddingLeft: 12,
    overflow: 'hidden',
  },
  input: {
    flex: 1,
    height: 48,
    color: text,
    fontSize: 14,
    fontWeight: '800',
  },
  addButton: {
    width: 58,
    height: 40,
    marginRight: 5,
    borderRadius: 9,
    backgroundColor: navy,
    alignItems: 'center',
    justifyContent: 'center',
  },
  addButtonText: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '900',
  },
  checkLine: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    borderWidth: 1,
    borderColor: line,
    borderRadius: 10,
    padding: 14,
    backgroundColor: '#FFFFFF',
  },
  progressCircle: {
    width: 130,
    height: 130,
    borderRadius: 65,
    backgroundColor: pale,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    marginTop: 42,
    position: 'relative',
  },
  progressCircleCompact: {
    width: 108,
    height: 108,
    borderRadius: 54,
    marginTop: 18,
  },
  progressSpinnerRing: {
    position: 'absolute',
    width: 130,
    height: 130,
    borderRadius: 65,
    borderWidth: 8,
    borderColor: '#DDF8E6',
    borderTopColor: navy,
    borderRightColor: '#AEE8BE',
  },
  progressSpinnerRingCompact: {
    width: 108,
    height: 108,
    borderRadius: 54,
    borderWidth: 7,
  },
  progressText: {
    color: navy,
    fontSize: 30,
    fontWeight: '900',
  },
  progressTextCompact: {
    fontSize: 24,
  },
  homeScanStatusCard: {
    borderColor: navy,
    backgroundColor: '#FFFFFF',
  },
  homeScanBadge: {
    overflow: 'hidden',
    borderRadius: 999,
    backgroundColor: navy,
    color: '#FFFFFF',
    fontSize: 10,
    fontWeight: '900',
    paddingHorizontal: 9,
    paddingVertical: 5,
  },
  homeScanBadgeMuted: {
    overflow: 'hidden',
    borderRadius: 999,
    backgroundColor: line,
    color: mutedText,
    fontSize: 10,
    fontWeight: '900',
    paddingHorizontal: 9,
    paddingVertical: 5,
  },
  miniProgressTrack: {
    height: 7,
    borderRadius: 7,
    backgroundColor: line,
    overflow: 'hidden',
    marginTop: 14,
  },
  miniProgressFill: {
    height: '100%',
    borderRadius: 7,
    backgroundColor: navy,
  },
  scanStatusActions: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 12,
  },
  scanStatusButton: {
    flex: 1,
    height: 34,
    borderRadius: 9,
    backgroundColor: navy,
    alignItems: 'center',
    justifyContent: 'center',
  },
  scanStatusButtonText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '900',
  },
  scanStatusCancel: {
    width: 62,
    height: 34,
    borderRadius: 9,
    borderWidth: 1,
    borderColor: navy,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFFFFF',
  },
  scanStatusCancelText: {
    color: navy,
    fontSize: 12,
    fontWeight: '900',
  },
  scanFloatingPanel: {
    borderWidth: 1,
    borderColor: line,
    borderRadius: 16,
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 16,
    paddingVertical: 18,
  },
  scanPercent: {
    color: navy,
    fontSize: 22,
    fontWeight: '900',
  },
  scanConditionLine: {
    color: mutedText,
    fontSize: 11,
    lineHeight: 16,
    fontWeight: '800',
    marginTop: 3,
    maxWidth: 190,
  },
  progressTrack: {
    height: 9,
    borderRadius: 9,
    backgroundColor: line,
    overflow: 'hidden',
    marginVertical: 20,
  },
  progressFill: {
    height: '100%',
    backgroundColor: navy,
  },
  progressActionRow: {
    width: '100%',
    flexDirection: 'row',
    gap: 10,
    marginTop: 2,
  },
  progressCancelButton: {
    flex: 1,
    height: 42,
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: navy,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  progressCancelButtonText: {
    color: navy,
    fontSize: 13,
    fontWeight: '900',
  },
  progressHomeButton: {
    flex: 1,
    height: 42,
    borderRadius: 12,
    backgroundColor: navy,
    alignItems: 'center',
    justifyContent: 'center',
  },
  progressHomeButtonText: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '900',
  },
  listNoticeText: {
    color: mutedText,
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '900',
    marginBottom: 4,
  },
  listNoticeDanger: {
    color: '#D65353',
  },
  selectAllRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingVertical: 8,
  },
  selectAllText: {
    flex: 1,
    color: text,
    fontSize: 14,
    fontWeight: '900',
  },
  filterText: {
    color: text,
    fontSize: 14,
    fontWeight: '900',
  },
  listCard: {
    minHeight: 72,
    borderWidth: 1,
    borderColor: line,
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    backgroundColor: '#FFFFFF',
  },
  resultSummary: {
    color: text,
    fontSize: 14,
    fontWeight: '900',
  },
  resultMetricGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  reviewMetricGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 18,
    marginBottom: 2,
  },
  resultMetricCard: {
    flex: 1,
    minWidth: 132,
    minHeight: 76,
    borderWidth: 0,
    borderColor: line,
    borderRadius: 20,
    backgroundColor: pale,
    paddingHorizontal: 16,
    paddingVertical: 12,
    justifyContent: 'center',
    gap: 8,
    ...gentleShadow,
  },
  recentHeroCard: {
    minHeight: 98,
    borderWidth: 0,
    borderColor: line,
    borderRadius: 20,
    backgroundColor: pale,
    paddingHorizontal: 16,
    paddingVertical: 14,
    justifyContent: 'center',
    gap: 8,
    ...gentleShadow,
  },
  recentHeroHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 14,
  },
  recentHeroDate: {
    color: text,
    fontSize: 22,
    fontWeight: '900',
  },
  recentHeroSizeValue: {
    color: text,
    textAlign: 'right',
    fontSize: 30,
    fontWeight: '900',
  },
  recentResultRow: {
    minHeight: 76,
    borderWidth: 0,
    borderColor: line,
    borderRadius: 18,
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 16,
    paddingVertical: 13,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    ...gentleShadow,
  },
  recentResultValue: {
    minWidth: 72,
    color: navy,
    textAlign: 'right',
    fontSize: 12,
    lineHeight: 18,
    fontWeight: '900',
  },
  carbonTotalCard: {
    minHeight: 104,
    borderWidth: 0,
    borderColor: line,
    borderRadius: 20,
    backgroundColor: pale,
    paddingHorizontal: 18,
    paddingVertical: 15,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    ...softShadow,
  },
  carbonTotalValue: {
    color: text,
    fontSize: 36,
    fontWeight: '900',
    marginTop: 5,
  },
  monthCarbonPill: {
    minHeight: 32,
    borderRadius: 16,
    backgroundColor: pale,
    borderWidth: 0,
    borderColor: line,
    paddingHorizontal: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  monthCarbonText: {
    color: navy,
    fontSize: 12,
    fontWeight: '900',
  },
  statsGraphCard: {
    minHeight: 204,
    borderWidth: 0,
    borderColor: line,
    borderRadius: 20,
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 16,
    paddingVertical: 14,
    gap: 12,
    ...softShadow,
  },
  statsLineChart: {
    borderRadius: 16,
  },
  statsChartClip: {
    width: '100%',
    overflow: 'hidden',
  },
  statsChartReveal: {
    overflow: 'hidden',
  },
  graphArea: {
    height: 142,
    flexDirection: 'row',
    alignItems: 'stretch',
    gap: 9,
  },
  graphYAxis: {
    width: 26,
    justifyContent: 'space-between',
    paddingBottom: 19,
    paddingTop: 8,
  },
  graphAxisText: {
    color: mutedText,
    fontSize: 10,
    fontWeight: '900',
    textAlign: 'right',
  },
  graphPlot: {
    flex: 1,
    position: 'relative',
    borderBottomWidth: 1,
    borderBottomColor: line,
    height: 122,
    paddingHorizontal: 2,
  },
  graphColumn: {
    width: 42,
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: 6,
    zIndex: 2,
  },
  graphValue: {
    color: navy,
    fontSize: 10,
    fontWeight: '900',
  },
  graphBar: {
    width: 26,
    borderTopLeftRadius: 8,
    borderTopRightRadius: 8,
    backgroundColor: navy,
  },
  lineGraphLayer: {
    position: 'absolute',
    left: 4,
    top: 8,
    width: 226,
    height: 116,
  },
  lineGraphSegment: {
    position: 'absolute',
    height: 3,
    borderRadius: 3,
    backgroundColor: navy,
    transformOrigin: '0px 1.5px',
  },
  lineGraphPointWrap: {
    position: 'absolute',
    width: 36,
    alignItems: 'center',
    gap: 4,
  },
  lineGraphPoint: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: navy,
    borderWidth: 2,
    borderColor: '#FFFFFF',
  },
  graphMonthLayer: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: -2,
    height: 18,
  },
  graphEmptyState: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 42,
    alignItems: 'center',
    justifyContent: 'center',
  },
  graphMonth: {
    position: 'absolute',
    width: 32,
    color: mutedText,
    fontSize: 11,
    fontWeight: '900',
    textAlign: 'center',
  },
  graphGridLineTop: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 8,
    height: 1,
    backgroundColor: line,
  },
  graphGridLineMiddle: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 56,
    height: 1,
    backgroundColor: line,
  },
  graphGridLineBottom: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 104,
    height: 1,
    backgroundColor: line,
  },
  statsGuideText: {
    color: mutedText,
    fontSize: 12,
    lineHeight: 18,
    fontWeight: '800',
    textAlign: 'center',
  },
  recentCleanupCard: {
    minHeight: 88,
    borderWidth: 0,
    borderColor: line,
    borderRadius: 20,
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 16,
    paddingVertical: 14,
    justifyContent: 'center',
    ...gentleShadow,
  },
  recentCleanupTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 11,
  },
  recentCleanupSizeValue: {
    minWidth: 116,
    marginLeft: 'auto',
    color: text,
    textAlign: 'right',
    fontSize: 30,
    lineHeight: 36,
    fontWeight: '900',
  },
  carbonBasisHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  helpCircleButton: {
    width: 26,
    height: 26,
    borderRadius: 13,
    borderWidth: 1,
    borderColor: line,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  helpCircleText: {
    color: navy,
    fontSize: 15,
    fontWeight: '900',
  },
  carbonBasisStandardBox: {
    borderWidth: 1,
    borderColor: line,
    borderRadius: 12,
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 14,
    paddingVertical: 14,
    gap: 12,
  },
  carbonBasisLine: {
    minHeight: 45,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  carbonBasisLineTitle: {
    color: text,
    fontSize: 14,
    fontWeight: '900',
  },
  carbonBasisLineDesc: {
    color: mutedText,
    fontSize: 10.5,
    lineHeight: 15,
    fontWeight: '800',
  },
  carbonBasisLineValue: {
    minWidth: 112,
    color: navy,
    fontSize: 17,
    lineHeight: 22,
    fontWeight: '900',
    textAlign: 'right',
  },
  carbonExampleCard: {
    minHeight: 82,
    borderWidth: 1,
    borderColor: line,
    borderRadius: 12,
    backgroundColor: pale,
    paddingHorizontal: 16,
    paddingVertical: 13,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  carbonExampleTitle: {
    color: text,
    fontSize: 18,
    lineHeight: 24,
    fontWeight: '900',
  },
  carbonNoticeCard: {
    marginTop: 'auto',
    borderWidth: 1,
    borderColor: '#E7D89B',
    borderRadius: 12,
    backgroundColor: '#FFF8D8',
    paddingHorizontal: 14,
    paddingVertical: 13,
    gap: 7,
  },
  carbonNoticeTitle: {
    color: text,
    fontSize: 12.5,
    lineHeight: 18,
    fontWeight: '900',
  },
  resultCategoryCard: {
    minHeight: 54,
    borderWidth: 0,
    borderColor: line,
    borderRadius: 18,
    backgroundColor: pale,
    paddingHorizontal: 14,
    paddingVertical: 8,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 9,
    ...gentleShadow,
  },
  resultCategoryMeta: {
    minWidth: 86,
    color: mutedText,
    textAlign: 'right',
    fontSize: 14.5,
    lineHeight: 18,
    fontWeight: '900',
  },
  reviewSummaryCard: {
    minHeight: 72,
    borderWidth: 0,
    borderColor: line,
    borderRadius: 18,
    backgroundColor: pale,
    paddingHorizontal: 16,
    paddingVertical: 13,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    ...gentleShadow,
  },
  reviewRedNumber: {
    color: '#C13A3A',
    fontWeight: '900',
  },
  resultGuideText: {
    marginTop: 6,
    color: text,
    textAlign: 'center',
    fontSize: 13,
    fontWeight: '900',
    textDecorationLine: 'underline',
  },
  resultWarningText: {
    color: '#C13A3A',
    fontSize: 12,
    lineHeight: 17,
    fontWeight: '900',
  },
  reviewWarningText: {
    marginTop: 10,
    color: '#C13A3A',
    fontSize: 12.5,
    lineHeight: 18,
    fontWeight: '900',
    textAlign: 'left',
  },
  detailMainTitle: {
    color: text,
    fontSize: 21,
    lineHeight: 27,
    fontWeight: '900',
  },
  detailSubMeta: {
    marginTop: -4,
    color: mutedText,
    fontSize: 12.5,
    lineHeight: 18,
    fontWeight: '900',
  },
  itemPreviewBox: {
    minHeight: 190,
    borderWidth: 1,
    borderColor: line,
    borderRadius: 10,
    backgroundColor: pale,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 16,
  },
  itemPreviewText: {
    color: mutedText,
    fontSize: 16,
    fontWeight: '900',
    textAlign: 'center',
  },
  mailBodyCard: {
    minHeight: 160,
    borderWidth: 1,
    borderColor: '#CFEFDB',
    borderRadius: 10,
    backgroundColor: pale,
    paddingHorizontal: 16,
    paddingVertical: 16,
    paddingRight: 48,
    justifyContent: 'flex-start',
  },
  mailBodyCardExpanded: {
    minHeight: 190,
  },
  mailBodyText: {
    color: mutedText,
    fontSize: 14,
    lineHeight: 21,
    fontWeight: '800',
  },
  mailBodyExpandButton: {
    position: 'absolute',
    right: 12,
    bottom: 12,
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: line,
    alignItems: 'center',
    justifyContent: 'center',
  },
  driveLinkCard: {
    minHeight: 160,
    borderWidth: 1,
    borderColor: '#CFEFDB',
    borderRadius: 10,
    backgroundColor: pale,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 18,
    paddingVertical: 18,
    gap: 10,
  },
  driveLinkIconButton: {
    width: 70,
    height: 70,
    alignItems: 'center',
    justifyContent: 'center',
  },
  driveLinkIconButtonDisabled: {
    opacity: 0.55,
  },
  driveLinkTitle: {
    color: text,
    fontSize: 15,
    fontWeight: '900',
    textAlign: 'center',
  },
  driveLinkDesc: {
    color: mutedText,
    fontSize: 12.5,
    lineHeight: 18,
    fontWeight: '800',
    textAlign: 'center',
  },
  detailInfoBox: {
    borderWidth: 1,
    borderColor: line,
    borderRadius: 10,
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 16,
    paddingVertical: 14,
    gap: 9,
  },
  detailInfoTitle: {
    color: text,
    fontSize: 14,
    fontWeight: '900',
  },
  detailInfoText: {
    color: mutedText,
    fontSize: 12.5,
    lineHeight: 19,
    fontWeight: '800',
  },
  deleteStatusRow: {
    minHeight: 70,
    borderWidth: 1,
    borderColor: line,
    borderRadius: 10,
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 16,
    paddingVertical: 13,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  deleteStatusRowDone: {
    borderColor: navy,
  },
  deleteStatusServiceIcon: {
    width: 30,
    height: 30,
  },
  deleteStatusText: {
    color: text,
    fontSize: 16,
    fontWeight: '900',
  },
  progressLabel: {
    marginTop: 8,
    color: text,
    fontSize: 13,
    fontWeight: '900',
  },
  progressRightText: {
    marginTop: -12,
    color: text,
    textAlign: 'right',
    fontSize: 13,
    fontWeight: '900',
  },
  remainingCapacityText: {
    color: text,
    textAlign: 'center',
    fontSize: 16,
    lineHeight: 22,
    fontWeight: '900',
    marginTop: -6,
    marginBottom: 8,
  },
  cleanupCheckCircle: {
    width: 118,
    height: 118,
    borderRadius: 59,
    borderWidth: 2,
    borderColor: navy,
    backgroundColor: pale,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    marginTop: 14,
  },
  cleanupCheckText: {
    color: navy,
    fontSize: 48,
    lineHeight: 54,
    fontWeight: '900',
  },
  cleanupTitle: {
    color: text,
    textAlign: 'center',
    fontSize: 24,
    lineHeight: 30,
    fontWeight: '900',
    marginVertical: 8,
  },
  cleanupMetricCard: {
    width: '47%',
    minHeight: 84,
    borderWidth: 1,
    borderColor: line,
    borderRadius: 10,
    backgroundColor: pale,
    paddingHorizontal: 16,
    paddingVertical: 13,
    justifyContent: 'center',
    gap: 6,
  },
  cleanupMetricValue: {
    color: text,
    fontSize: 22,
    fontWeight: '900',
  },
  cleanupCountCard: {
    minHeight: 124,
    gap: 12,
  },
  cleanupCountInnerRow: {
    flexDirection: 'row',
    gap: 10,
  },
  cleanupCountInnerCard: {
    flex: 1,
    minHeight: 58,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: line,
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  cleanupCountLabel: {
    color: text,
    fontSize: 14,
    fontWeight: '900',
  },
  cleanupCountValue: {
    color: text,
    fontSize: 21,
    fontWeight: '900',
  },
  cleanupCapacityCard: {
    minHeight: 152,
    gap: 13,
  },
  cleanupCapacityMetricRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  cleanupCapacityValue: {
    color: text,
    fontSize: 23,
    fontWeight: '900',
  },
  cleanupDriveBarTrack: {
    height: 18,
    borderRadius: 18,
    backgroundColor: line,
    overflow: 'hidden',
    position: 'relative',
  },
  cleanupDriveCurrentBar: {
    height: '100%',
    borderTopLeftRadius: 18,
    borderBottomLeftRadius: 18,
    borderTopRightRadius: 0,
    borderBottomRightRadius: 0,
    backgroundColor: navy,
  },
  cleanupDriveReclaimedBar: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    minWidth: 10,
    borderTopLeftRadius: 0,
    borderBottomLeftRadius: 0,
    borderTopRightRadius: 18,
    borderBottomRightRadius: 18,
    backgroundColor: navy,
  },
  cleanupDriveTotalLabel: {
    marginTop: -8,
    color: mutedText,
    textAlign: 'right',
    fontSize: 11,
    fontWeight: '900',
  },
  cleanupButtonSpacer: {
    flex: 1,
    minHeight: 44,
  },
  carbonStandardCard: {
    minHeight: 60,
    borderWidth: 1,
    borderColor: line,
    borderRadius: 10,
    backgroundColor: pale,
    paddingHorizontal: 16,
    paddingVertical: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  twoButtons: {
    flexDirection: 'row',
    gap: 10,
  },
  segment: {
    height: 42,
    borderRadius: 18,
    borderWidth: 0,
    borderColor: line,
    padding: 3,
    flexDirection: 'row',
    backgroundColor: '#FFFFFF',
    ...gentleShadow,
  },
  segmentItem: {
    flex: 1,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
  segmentActive: {
    backgroundColor: navy,
  },
  segmentSubActive: {
    backgroundColor: '#E9FFF0',
    borderWidth: 0,
    borderColor: '#CDEFD8',
  },
  segmentText: {
    color: text,
    fontSize: 12,
    fontWeight: '900',
  },
  segmentTextActive: {
    color: '#FFFFFF',
  },
  storagePrimaryTabs: {
    height: 48,
    marginTop: -10,
    flexDirection: 'row',
    borderWidth: 0,
    borderColor: line,
    borderRadius: 18,
    overflow: 'hidden',
    backgroundColor: '#FFFFFF',
    ...gentleShadow,
  },
  storagePrimaryTab: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    borderRightWidth: 1,
    borderRightColor: line,
  },
  storagePrimaryTabActive: {
    backgroundColor: navy,
  },
  storagePrimaryTabText: {
    color: text,
    fontSize: 14,
    fontWeight: '900',
  },
  storagePrimaryTabTextActive: {
    color: '#FFFFFF',
  },
  storageTrashNoticeBlock: {
    borderTopWidth: 1,
    borderColor: line,
    paddingTop: 12,
    paddingHorizontal: 2,
  },
  storageTrashNoticeText: {
    color: mutedText,
    fontSize: 12.5,
    lineHeight: 18,
    fontWeight: '900',
  },
  storageSummaryBar: {
    minHeight: 50,
    borderWidth: 0,
    borderColor: line,
    borderRadius: 18,
    backgroundColor: pale,
    paddingHorizontal: 16,
    paddingVertical: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
    ...gentleShadow,
  },
  storageSummaryText: {
    color: text,
    fontSize: 13,
    fontWeight: '900',
  },
  storageFilterText: {
    color: text,
    fontSize: 12,
    fontWeight: '900',
  },
  storagePathCard: {
    minHeight: 42,
    borderTopWidth: 1,
    borderColor: line,
    borderRadius: 0,
    backgroundColor: 'transparent',
    paddingHorizontal: 2,
    paddingTop: 12,
    paddingBottom: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  storagePathCardAfterTrashNotice: {
    borderTopWidth: 0,
    paddingTop: 0,
  },
  storageLooseList: {
    gap: 10,
    paddingBottom: 90,
  },
  folderListBox: {
    borderWidth: 0,
    borderColor: line,
    borderRadius: 20,
    backgroundColor: '#FFFFFF',
    padding: 7,
    gap: 7,
    ...softShadow,
  },
  folderListScroll: {
    maxHeight: 268,
  },
  folderListContent: {
    gap: 8,
    paddingBottom: 2,
  },
  storagePagerCard: {
    minHeight: 42,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  storageBreadcrumbRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    flex: 1,
    gap: 6,
    minWidth: 0,
    paddingRight: 8,
  },
  storageBreadcrumbPressable: {
    maxWidth: '100%',
  },
  storageBreadcrumbText: {
    color: text,
    fontSize: 14,
    fontWeight: '900',
  },
  storageBreadcrumbCurrent: {
    color: navy,
    fontSize: 16,
  },
  storageBreadcrumbDivider: {
    color: text,
    fontSize: 18,
    fontWeight: '900',
  },
  storagePathCountText: {
    color: mutedText,
    fontSize: 12,
    fontWeight: '900',
    flexShrink: 0,
    minWidth: 34,
    textAlign: 'right',
  },
  storageItemCard: {
    minHeight: 78,
    borderWidth: 0,
    borderColor: line,
    borderRadius: 20,
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 14,
    paddingVertical: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    ...gentleShadow,
  },
  storageItemCardCompact: {
    minHeight: 56,
    paddingVertical: 8,
  },
  storageListBox: {
    height: 302,
    borderWidth: 0,
    borderColor: line,
    borderRadius: 20,
    backgroundColor: '#FFFFFF',
    padding: 7,
    gap: 7,
    ...softShadow,
  },
  storageListScroll: {
    flex: 1,
  },
  storageListContent: {
    gap: 8,
    paddingBottom: 1,
  },
  storageLoadingCard: {
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    paddingVertical: 28,
  },
  storagePagerRow: {
    minHeight: 32,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: 8,
    paddingHorizontal: 2,
  },
  storagePagerText: {
    color: text,
    fontSize: 14,
    fontWeight: '900',
  },
  storagePagerButtons: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
  },
  storagePagerButton: {
    width: 30,
    height: 30,
    alignItems: 'center',
    justifyContent: 'center',
  },
  storagePagerButtonDisabled: {
    opacity: 0.42,
  },
  storagePagerGlyph: {
    color: text,
    fontSize: 25,
    lineHeight: 27,
    fontWeight: '900',
  },
  storagePagerGlyphDisabled: {
    color: mutedText,
  },
  storageDriveItemPressArea: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  storageChevronButton: {
    width: 38,
    height: 44,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: -8,
  },
  storageTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flexWrap: 'wrap',
  },
  storageTitleRowCompact: {
    marginTop: -2,
  },
  storageCompactMeta: {
    color: mutedText,
    fontSize: 11.5,
    lineHeight: 15,
    fontWeight: '800',
    marginTop: 2,
  },
  storageRightSize: {
    minWidth: 48,
    color: mutedText,
    fontSize: 12,
    fontWeight: '900',
    textAlign: 'right',
  },
  storageRightSizeDanger: {
    color: '#C13A3A',
  },
  storageSubtitle: {
    color: text,
    fontSize: 12.5,
    fontWeight: '900',
    marginTop: 2,
    marginBottom: 2,
  },
  storageBadge: {
    height: 24,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: line,
    backgroundColor: '#E9FFF0',
    paddingHorizontal: 9,
    justifyContent: 'center',
  },
  storageBadgeWarn: {
    backgroundColor: '#FFF6D9',
    borderColor: '#D8C16A',
  },
  storageBadgeText: {
    color: navy,
    fontSize: 10.5,
    fontWeight: '900',
  },
  storageSelectAllRowInBox: {
    minHeight: 34,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingHorizontal: 4,
  },
  permissionRevokedCard: {
    marginTop: 26,
    minHeight: 392,
    borderWidth: 1,
    borderColor: line,
    borderRadius: 12,
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 26,
    paddingVertical: 42,
    alignItems: 'center',
    gap: 12,
  },
  permissionRevokedIcon: {
    width: 104,
    height: 104,
    borderRadius: 52,
    borderWidth: 1.5,
    borderColor: line,
    backgroundColor: pale,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 8,
  },
  permissionRevokedIconText: {
    color: navy,
    fontSize: 40,
    fontWeight: '900',
  },
  permissionRevokedTitle: {
    color: text,
    fontSize: 19,
    lineHeight: 25,
    fontWeight: '900',
    textAlign: 'center',
  },
  permissionRevokedDesc: {
    color: mutedText,
    fontSize: 12.5,
    lineHeight: 18,
    fontWeight: '900',
    textAlign: 'center',
  },
  storageDeleteOverlay: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    zIndex: 42,
    backgroundColor: 'rgba(32, 33, 36, 0.12)',
    justifyContent: 'flex-end',
  },
  storageDeleteSheet: {
    borderTopLeftRadius: 22,
    borderTopRightRadius: 22,
    borderWidth: 1,
    borderColor: line,
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 18,
    gap: 13,
    shadowColor: '#000000',
    shadowOpacity: 0.14,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: -6 },
    elevation: 16,
  },
  storageDeleteTitle: {
    color: text,
    textAlign: 'center',
    fontSize: 22,
    lineHeight: 29,
    fontWeight: '900',
  },
  storageDeleteWarningBox: {
    borderWidth: 1,
    borderColor: '#DFA7A7',
    borderRadius: 10,
    backgroundColor: '#FBE2E0',
    paddingHorizontal: 15,
    paddingVertical: 13,
    gap: 8,
  },
  storageDeleteInfoBox: {
    borderWidth: 1,
    borderColor: line,
    borderRadius: 10,
    backgroundColor: pale,
    paddingHorizontal: 15,
    paddingVertical: 13,
    gap: 8,
  },
  storageDeleteWarningTitle: {
    color: text,
    fontSize: 14,
    fontWeight: '900',
  },
  storageDeleteWarningText: {
    color: mutedText,
    fontSize: 12,
    lineHeight: 18,
    fontWeight: '900',
  },
  storageDeleteSummaryBox: {
    borderWidth: 1,
    borderColor: line,
    borderRadius: 10,
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 15,
    paddingVertical: 13,
    gap: 8,
  },
  storageDeleteDangerButton: {
    height: 50,
    borderRadius: 10,
    backgroundColor: '#E4312B',
    alignItems: 'center',
    justifyContent: 'center',
  },
  storageRestoreInfoBox: {
    minHeight: 90,
    borderRadius: 18,
    backgroundColor: pale,
    padding: 16,
    justifyContent: 'center',
    gap: 6,
  },
  storageRestoreButton: {
    height: 50,
    borderRadius: 10,
    backgroundColor: '#6FCF85',
    alignItems: 'center',
    justifyContent: 'center',
  },
  restoreButtonDisabled: {
    opacity: 0.45,
  },
  fileOutlineIcon: {
    width: 30,
    height: 34,
    borderRadius: 7,
    borderWidth: 2,
    borderColor: navy,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  fileOutlineFold: {
    position: 'absolute',
    top: -2,
    right: -2,
    width: 12,
    height: 12,
    borderLeftWidth: 2,
    borderBottomWidth: 2,
    borderColor: navy,
    backgroundColor: pale,
    transform: [{ rotate: '45deg' }],
  },
  fileDocLineWide: {
    width: 16,
    height: 2,
    borderRadius: 2,
    backgroundColor: navy,
    marginTop: 7,
    marginBottom: 4,
  },
  fileDocLine: {
    width: 13,
    height: 2,
    borderRadius: 2,
    backgroundColor: navy,
    marginBottom: 4,
  },
  fileDocLineShort: {
    width: 9,
    height: 2,
    borderRadius: 2,
    backgroundColor: navy,
  },
  fileImageSun: {
    position: 'absolute',
    top: 10,
    right: 7,
    width: 5,
    height: 5,
    borderRadius: 3,
    backgroundColor: navy,
  },
  fileImageMountain: {
    position: 'absolute',
    left: 7,
    bottom: 8,
    width: 16,
    height: 16,
    borderLeftWidth: 2,
    borderBottomWidth: 2,
    borderColor: navy,
    transform: [{ rotate: '-45deg' }],
  },
  fileZipRail: {
    width: 8,
    height: 22,
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  fileZipTooth: {
    width: 6,
    height: 4,
    borderRadius: 1,
    borderWidth: 1.5,
    borderColor: navy,
    backgroundColor: pale,
  },
  trashOutlineIcon: {
    width: 30,
    height: 34,
    alignItems: 'center',
    justifyContent: 'flex-end',
  },
  trashOutlineIconCompact: {
    transform: [{ scale: 0.92 }],
  },
  trashLid: {
    position: 'absolute',
    top: 8,
    width: 23,
    height: 3,
    borderRadius: 3,
    backgroundColor: navy,
  },
  trashHandle: {
    position: 'absolute',
    top: 4,
    width: 10,
    height: 5,
    borderTopWidth: 2,
    borderLeftWidth: 2,
    borderRightWidth: 2,
    borderColor: navy,
    borderTopLeftRadius: 4,
    borderTopRightRadius: 4,
  },
  trashBody: {
    width: 22,
    height: 23,
    borderWidth: 2,
    borderTopWidth: 0,
    borderColor: navy,
    borderBottomLeftRadius: 6,
    borderBottomRightRadius: 6,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 4,
  },
  trashLine: {
    width: 2,
    height: 13,
    borderRadius: 2,
    backgroundColor: navy,
  },
  trashDangerBorder: {
    borderColor: '#D65353',
  },
  trashDangerFill: {
    backgroundColor: '#D65353',
  },
  folderTypeIcon: {
    backgroundColor: '#FFF4CC',
    borderColor: '#D7B44A',
  },
  folderTypeText: {
    color: '#8A6500',
    fontSize: 16,
  },
  storageHintText: {
    color: mutedText,
    fontSize: 10.5,
    fontWeight: '800',
  },
  storageFolderOpenButton: {
    minWidth: 32,
    height: 44,
    alignItems: 'flex-end',
    justifyContent: 'center',
  },
  driveMovePanel: {
    borderWidth: 1,
    borderColor: navy,
    borderRadius: 14,
    backgroundColor: '#FFFFFF',
    padding: 14,
    gap: 10,
  },
  driveMoveTargets: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  driveMoveTarget: {
    minHeight: 34,
    borderRadius: 17,
    borderWidth: 1,
    borderColor: line,
    backgroundColor: pale,
    paddingHorizontal: 12,
    justifyContent: 'center',
  },
  driveMoveTargetText: {
    color: navy,
    fontSize: 11,
    fontWeight: '900',
  },
  storageMoveSheet: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    maxHeight: '78%',
    borderTopLeftRadius: 22,
    borderTopRightRadius: 22,
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 20,
    paddingTop: 8,
    paddingBottom: 24,
    gap: 14,
    shadowColor: '#000000',
    shadowOpacity: 0.14,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: -6 },
    elevation: 16,
  },
  storageMoveCurrentBox: {
    borderWidth: 1,
    borderColor: line,
    borderRadius: 14,
    backgroundColor: pale,
    paddingHorizontal: 14,
    paddingVertical: 12,
    gap: 4,
  },
  storageMoveTargetList: {
    gap: 8,
  },
  storageMoveTargetRow: {
    minHeight: 64,
    borderWidth: 1,
    borderColor: line,
    borderRadius: 14,
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 12,
    paddingVertical: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  filterSheet: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    borderTopLeftRadius: 22,
    borderTopRightRadius: 22,
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 28,
    gap: 12,
  },
  filterSectionTitle: {
    color: text,
    fontSize: 14,
    fontWeight: '900',
    marginTop: 4,
  },
  settingsProfileCard: {
    minHeight: 76,
    borderWidth: 1,
    borderColor: line,
    borderRadius: 10,
    paddingHorizontal: 16,
    paddingVertical: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    backgroundColor: pale,
  },
  accountHeroCard: {
    minHeight: 108,
    borderWidth: 1,
    borderColor: line,
    borderRadius: 10,
    paddingHorizontal: 16,
    paddingVertical: 16,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    backgroundColor: pale,
  },
  avatarCircle: {
    width: 58,
    height: 58,
    borderRadius: 29,
    backgroundColor: navy,
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarImage: {
    width: 58,
    height: 58,
    borderRadius: 29,
    backgroundColor: line,
  },
  avatarText: {
    color: '#FFFFFF',
    fontSize: 24,
    fontWeight: '900',
  },
  infoTitleLarge: {
    color: text,
    fontSize: 16,
    fontWeight: '900',
  },
  profileConnectionText: {
    color: mutedText,
    fontSize: 12,
    lineHeight: 18,
    fontWeight: '900',
  },
  smallPill: {
    minWidth: 50,
    height: 28,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: line,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 10,
  },
  smallPillText: {
    color: navy,
    fontSize: 11,
    fontWeight: '900',
  },
  outlineMiniPill: {
    alignSelf: 'flex-start',
    marginTop: 8,
    height: 25,
    borderRadius: 13,
    borderWidth: 1,
    borderColor: line,
    paddingHorizontal: 14,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFFFFF',
  },
  outlineMiniPillText: {
    color: navy,
    fontSize: 11,
    fontWeight: '900',
  },
  groupCard: {
    borderWidth: 0,
    borderColor: line,
    borderRadius: 18,
    backgroundColor: '#FFFFFF',
    overflow: 'hidden',
    ...gentleShadow,
  },
  thinDivider: {
    height: 1,
    backgroundColor: line,
    marginHorizontal: 16,
  },
  settingPlainRow: {
    minHeight: 74,
    paddingHorizontal: 16,
    paddingVertical: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    backgroundColor: '#FFFFFF',
  },
  serviceLinkRow: {
    minHeight: 84,
    paddingHorizontal: 16,
    paddingVertical: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    backgroundColor: '#FFFFFF',
  },
  serviceIconBox: {
    width: 46,
    height: 46,
    borderRadius: 10,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  serviceIconImage: {
    width: 34,
    height: 34,
  },
  connectedServiceIcon: {
    width: 28,
    height: 28,
  },
  connectedPill: {
    alignSelf: 'flex-start',
    marginTop: 6,
    height: 25,
    borderRadius: 13,
    borderWidth: 1,
    borderColor: line,
    backgroundColor: '#E9FFF0',
    paddingHorizontal: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  disconnectedPill: {
    backgroundColor: '#F1F3F4',
  },
  connectedPillText: {
    color: navy,
    fontSize: 11,
    fontWeight: '900',
  },
  disconnectedPillText: {
    color: mutedText,
  },
  connectedCheckingRow: {
    alignSelf: 'flex-start',
    marginTop: 6,
    minHeight: 25,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  connectedCheckingText: {
    color: mutedText,
    fontSize: 11,
    fontWeight: '900',
  },
  scopeCard: {
    minHeight: 70,
    borderWidth: 1,
    borderColor: line,
    borderRadius: 10,
    backgroundColor: pale,
    paddingHorizontal: 16,
    paddingVertical: 14,
    justifyContent: 'center',
  },
  scopeTitle: {
    color: text,
    fontSize: 13,
    fontWeight: '900',
    marginBottom: 6,
  },
  scopeDesc: {
    color: mutedText,
    fontSize: 12,
    lineHeight: 18,
    fontWeight: '900',
  },
  keywordConditionCard: {
    borderWidth: 1,
    borderColor: line,
    borderRadius: 10,
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 16,
    paddingVertical: 14,
    gap: 10,
  },
  keywordConditionSummary: {
    color: mutedText,
    fontSize: 12,
    lineHeight: 17,
    fontWeight: '800',
  },
  rowBetween: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  versionText: {
    color: mutedText,
    fontSize: 11,
    fontWeight: '900',
    textAlign: 'center',
    marginTop: 10,
    paddingTop: 0,
  },
  settingsBottomSpacer: {
    height: 72,
  },
  privacyWithdrawButton: {
    height: 50,
    borderRadius: 10,
    borderWidth: 1.5,
    borderColor: '#D92F36',
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 6,
  },
  privacyWithdrawText: {
    color: '#D92F36',
    fontSize: 15,
    fontWeight: '900',
  },
  summaryTintCard: {
    minHeight: 76,
    borderWidth: 1,
    borderColor: line,
    borderRadius: 10,
    paddingHorizontal: 16,
    paddingVertical: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: pale,
  },
  withdrawModalCard: {
    borderWidth: 1,
    borderColor: line,
    borderRadius: 16,
    paddingHorizontal: 18,
    paddingVertical: 12,
    gap: 14,
    backgroundColor: '#FFFFFF',
  },
  sheetOverlay: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    zIndex: 30,
    justifyContent: 'flex-end',
    backgroundColor: 'rgba(32, 33, 36, 0.10)',
  },
  deleteConfirmOverlay: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    zIndex: 40,
    backgroundColor: 'rgba(32, 33, 36, 0.12)',
    justifyContent: 'flex-end',
  },
  deleteApprovalPanel: {
    marginHorizontal: 14,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: line,
    borderRadius: 18,
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 18,
    paddingTop: 12,
    paddingBottom: 18,
    gap: 12,
    shadowColor: '#000000',
    shadowOpacity: 0.15,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 8 },
    elevation: 16,
  },
  deleteApprovalTitle: {
    color: text,
    fontSize: 20,
    lineHeight: 27,
    fontWeight: '900',
  },
  deleteApprovalDesc: {
    color: mutedText,
    fontSize: 13,
    lineHeight: 19,
    fontWeight: '900',
  },
  deleteApprovalInfoBox: {
    borderWidth: 1,
    borderColor: line,
    borderRadius: 12,
    backgroundColor: pale,
    paddingHorizontal: 14,
    paddingVertical: 12,
    gap: 7,
  },
  deleteApprovalInfoTitle: {
    color: text,
    fontSize: 14,
    fontWeight: '900',
  },
  deleteApprovalInfoText: {
    color: mutedText,
    fontSize: 12.5,
    lineHeight: 18,
    fontWeight: '800',
  },
  helpPopupOverlay: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    zIndex: 45,
    backgroundColor: 'rgba(32, 33, 36, 0.10)',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 28,
  },
  carbonHelpPopupCard: {
    width: '100%',
    borderWidth: 1,
    borderColor: line,
    borderRadius: 14,
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 18,
    paddingVertical: 18,
    gap: 10,
    shadowColor: '#000000',
    shadowOpacity: 0.14,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 8 },
    elevation: 18,
  },
  carbonHelpTitle: {
    color: text,
    fontSize: 14,
    lineHeight: 19,
    fontWeight: '900',
    textAlign: 'center',
  },
  carbonFormulaText: {
    color: navy,
    fontSize: 15,
    lineHeight: 21,
    fontWeight: '900',
    textAlign: 'center',
  },
  withdrawSheet: {
    borderTopLeftRadius: 22,
    borderTopRightRadius: 22,
    borderWidth: 1,
    borderColor: line,
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 18,
    gap: 13,
    shadowColor: '#000000',
    shadowOpacity: 0.14,
    shadowRadius: 18,
    elevation: 10,
  },
  keywordSheet: {
    borderTopLeftRadius: 22,
    borderTopRightRadius: 22,
    borderWidth: 1,
    borderColor: line,
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 14,
    gap: 9,
    shadowColor: '#000000',
    shadowOpacity: 0.14,
    shadowRadius: 18,
    elevation: 10,
  },
  keywordChoiceSheet: {
    borderTopLeftRadius: 22,
    borderTopRightRadius: 22,
    borderWidth: 1,
    borderColor: line,
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 18,
    gap: 12,
    shadowColor: '#000000',
    shadowOpacity: 0.14,
    shadowRadius: 18,
    elevation: 10,
  },
  keywordChoiceRow: {
    minHeight: 72,
    borderWidth: 1,
    borderColor: line,
    borderRadius: 12,
    backgroundColor: pale,
    paddingHorizontal: 14,
    paddingVertical: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  modalHandle: {
    width: 52,
    height: 5,
    borderRadius: 3,
    backgroundColor: '#DFF6E6',
    alignSelf: 'center',
    marginBottom: 8,
  },
  modalHandleHitArea: {
    alignSelf: 'center',
    minWidth: 92,
    minHeight: 28,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: -2,
  },
  modalTitle: {
    color: text,
    textAlign: 'center',
    fontSize: 20,
    fontWeight: '900',
  },
  modalClose: {
    color: mutedText,
    fontSize: 28,
    fontWeight: '900',
    lineHeight: 30,
  },
  warningCard: {
    borderWidth: 1,
    borderColor: line,
    borderRadius: 10,
    backgroundColor: '#FFF6D8',
    paddingHorizontal: 14,
    paddingVertical: 14,
    gap: 10,
  },
  warningText: {
    color: text,
    fontSize: 12,
    lineHeight: 18,
    fontWeight: '900',
  },
  recommendChip: {
    height: 34,
    borderRadius: 17,
    borderWidth: 1,
    borderColor: line,
    paddingHorizontal: 14,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFFFFF',
  },
  recommendChipText: {
    color: navy,
    fontSize: 12,
    fontWeight: '900',
  },
  dangerButton: {
    height: 50,
    borderRadius: 10,
    backgroundColor: '#D92F36',
    alignItems: 'center',
    justifyContent: 'center',
  },
  dangerButtonDisabled: {
    opacity: 0.45,
  },
  dangerText: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '900',
  },
  restoreText: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '900',
  },
  withdrawActionRow: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 2,
  },
  sheetCancelButton: {
    flex: 1,
    height: 50,
    borderRadius: 10,
    borderWidth: 1.5,
    borderColor: navy,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFFFFF',
  },
  sheetDangerButton: {
    flex: 1.35,
    height: 50,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#D92F36',
  },
  toggleRow: {
    minHeight: 72,
    borderWidth: 0,
    borderColor: line,
    borderRadius: 18,
    paddingHorizontal: 14,
    paddingVertical: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    backgroundColor: '#FFFFFF',
    ...gentleShadow,
  },
  toggleRowPlain: {
    borderWidth: 0,
    borderRadius: 0,
    minHeight: 74,
    paddingHorizontal: 16,
    backgroundColor: '#FFFFFF',
    shadowOpacity: 0,
    elevation: 0,
  },
  toggleRowTint: {
    backgroundColor: pale,
  },
  toggle: {
    width: 48,
    height: 28,
    borderRadius: 14,
    padding: 3,
    backgroundColor: '#DFF6E6',
  },
  toggleOn: {
    backgroundColor: navy,
  },
  toggleKnob: {
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: '#FFFFFF',
  },
  toggleKnobOn: {
    transform: [{ translateX: 20 }],
  },
  floatingScanButton: {
    position: 'absolute',
    right: 18,
    bottom: 78,
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: '#DDF8E6',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 80,
    elevation: 9,
    shadowColor: '#57C879',
    shadowOpacity: 0.22,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
  },
  floatingSmallButton: {
    right: 22,
    width: 48,
    height: 48,
    borderRadius: 24,
  },
  floatingTrashButton: {
    borderWidth: 2,
    borderColor: '#D65353',
    backgroundColor: '#FFFFFF',
    shadowColor: '#D65353',
    shadowOpacity: 0.16,
  },
  floatingDeleteButton: {
    borderWidth: 2,
    borderColor: line,
    backgroundColor: '#FFFFFF',
    shadowColor: '#000000',
    shadowOpacity: 0.09,
  },
  floatingRestoreButton: {
    borderWidth: 2,
    borderColor: line,
    backgroundColor: '#FFFFFF',
    shadowColor: '#000000',
    shadowOpacity: 0.08,
  },
  floatingScanLogo: {
    width: 38,
    height: 38,
    borderRadius: 11,
  },
  bottomNav: {
    height: 64,
    borderTopWidth: 1,
    borderTopColor: line,
    flexDirection: 'row',
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 12,
  },
  navButton: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 3,
  },
  navIconFrame: {
    width: 24,
    height: 22,
    alignItems: 'center',
    justifyContent: 'center',
  },
  navLabel: {
    color: mutedText,
    fontSize: 10,
    fontWeight: '900',
  },
  navLabelActive: {
    color: navy,
  },
  navIconActiveFill: {
    backgroundColor: navy,
  },
  navHomeImage: {
    width: 20,
    height: 20,
  },
  navHomeImageInactive: {
    opacity: 0.72,
  },
  navHomeRoofLeft: {
    position: 'absolute',
    top: 5,
    left: 3.2,
    width: 15.5,
    height: 4.6,
    borderRadius: 1,
    backgroundColor: mutedText,
    transform: [{ rotate: '-43deg' }],
  },
  navHomeRoofRight: {
    position: 'absolute',
    top: 5,
    right: 3.2,
    width: 15.5,
    height: 4.6,
    borderRadius: 1,
    backgroundColor: mutedText,
    transform: [{ rotate: '43deg' }],
  },
  navHomeLeftWall: {
    position: 'absolute',
    left: 3.5,
    bottom: 2.5,
    width: 4.8,
    height: 12.5,
    backgroundColor: mutedText,
  },
  navHomeRightWall: {
    position: 'absolute',
    right: 3.5,
    bottom: 2.5,
    width: 4.8,
    height: 12.5,
    backgroundColor: mutedText,
  },
  navHomeBase: {
    position: 'absolute',
    left: 3.5,
    right: 3.5,
    bottom: 2.5,
    height: 4.8,
    backgroundColor: mutedText,
  },
  navHomeDoorCut: {
    position: 'absolute',
    bottom: 2.5,
    width: 6.4,
    height: 9.2,
    backgroundColor: '#FFFFFF',
  },
  navLocker: {
    width: 18,
    height: 21,
    borderRadius: 4,
    borderWidth: 2.2,
    borderColor: mutedText,
    backgroundColor: '#FFFFFF',
    overflow: 'hidden',
  },
  navLockerActive: {
    borderColor: navy,
    backgroundColor: '#E9FFF0',
  },
  navLockerDoor: {
    flex: 1,
    borderLeftWidth: 1.5,
    borderLeftColor: line,
    alignItems: 'center',
    paddingTop: 4,
  },
  navLockerDoorActive: {
    borderLeftColor: navy,
  },
  navLockerVent: {
    width: 8.5,
    height: 1.8,
    borderRadius: 1,
    backgroundColor: mutedText,
    marginBottom: 2,
  },
  navLockerHandle: {
    position: 'absolute',
    right: 3,
    top: 10,
    width: 2.8,
    height: 5.4,
    borderRadius: 2,
    backgroundColor: mutedText,
  },
  navHistoryWrap: {
    width: 22,
    height: 22,
    borderWidth: 2,
    borderColor: mutedText,
    borderRadius: 5,
    paddingHorizontal: 4,
    paddingVertical: 4,
    justifyContent: 'space-between',
    backgroundColor: '#FFFFFF',
  },
  navHistoryWrapActive: {
    borderColor: navy,
    backgroundColor: '#E9FFF0',
  },
  navHistoryLine: {
    height: 2,
    borderRadius: 2,
    backgroundColor: mutedText,
  },
  navHistoryChart: {
    width: 23,
    height: 20,
    position: 'relative',
  },
  navHistoryAxis: {
    position: 'absolute',
    left: 2,
    right: 1,
    bottom: 3,
    height: 2.2,
    borderRadius: 2,
    backgroundColor: mutedText,
  },
  navHistorySegment: {
    position: 'absolute',
    height: 3,
    borderRadius: 3,
    backgroundColor: mutedText,
  },
  navHistorySegmentOne: {
    left: 4,
    bottom: 7,
    width: 9.5,
    transform: [{ rotate: '-28deg' }],
  },
  navHistorySegmentTwo: {
    right: 3,
    bottom: 10,
    width: 10.5,
    transform: [{ rotate: '34deg' }],
  },
  navHistoryDot: {
    position: 'absolute',
    width: 4.6,
    height: 4.6,
    borderRadius: 3,
    backgroundColor: mutedText,
  },
  navHistoryDotOne: {
    left: 2.5,
    bottom: 6,
  },
  navHistoryDotTwo: {
    left: 10,
    bottom: 10.5,
  },
  navHistoryDotThree: {
    right: 1.5,
    bottom: 15,
  },
  navHistoryActiveFill: {
    backgroundColor: navy,
  },
  navGearWrap: {
    width: 24,
    height: 24,
    alignItems: 'center',
    justifyContent: 'center',
  },
  navGearRing: {
    width: 17.5,
    height: 17.5,
    borderRadius: 9,
    borderWidth: 0,
    backgroundColor: mutedText,
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 2,
  },
  navGearRingActive: {
    backgroundColor: navy,
  },
  navGearCore: {
    width: 8.2,
    height: 8.2,
    borderRadius: 5,
    backgroundColor: '#FFFFFF',
    borderWidth: 0,
  },
  navGearCoreActive: {
    backgroundColor: '#FFFFFF',
  },
  navGearTooth: {
    position: 'absolute',
    width: 5.4,
    height: 7.2,
    borderRadius: 1.4,
    backgroundColor: mutedText,
    zIndex: 1,
  },
  navGearTop: {
    top: 0.5,
  },
  navGearTopRight: {
    top: 2.6,
    right: 2.6,
    transform: [{ rotate: '45deg' }],
  },
  navGearRight: {
    right: 0.5,
    transform: [{ rotate: '90deg' }],
  },
  navGearBottomRight: {
    right: 2.6,
    bottom: 2.6,
    transform: [{ rotate: '-45deg' }],
  },
  navGearBottom: {
    bottom: 0.5,
  },
  navGearBottomLeft: {
    bottom: 2.6,
    left: 2.6,
    transform: [{ rotate: '45deg' }],
  },
  navGearLeft: {
    left: 0.5,
    transform: [{ rotate: '90deg' }],
  },
  navGearTopLeft: {
    top: 2.6,
    left: 2.6,
    transform: [{ rotate: '-45deg' }],
  },
});

